spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

company-house:
  base-url: https://api.company-information.service.gov.uk
  api-key: ${COMPANY_HOUSE_API_KEY}

springdoc:
  api-docs:
    path: /api-docs